Escribir un arreglo con números enteros del 0 al 9. Pista: arange

Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [4]:
import numpy as np

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = np.linspace(0,99,100)

In [23]:
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3
Pista: mask

In [29]:
c = np.arange(10,101)
mask = ((c % 3) ==0)
c[mask]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Crear un arreglo de ceros de shape (5,10).

Reemplazar la segunda y cuarta fila con unos

Reemplazar la tercera y octava columna con dos (2).

In [67]:
a = np.zeros(50).reshape(5,10)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
tmp = np.full((1, 10), 1)
a[1] = tmp
a[3] = tmp
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
for j in range(len(a)):
    a[j][7] = 2
    a[j][2] = 2
a

array([[0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.]])